<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="199" started-at="2021-01-31T06:41:30 IST" finished-at="2021-01-31T06:41:30 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="199" started-at="2021-01-31T06:41:30 IST" finished-at="2021-01-31T06:41:30 IST">
      <class name="com.automation.PracticeSeleniumFramework.JavaPractice.RunTimeException">
        <test-method status="PASS" signature="testException()[pri:0, instance:com.automation.PracticeSeleniumFramework.JavaPractice.RunTimeException@67205a84]" name="testException" duration-ms="37" started-at="2021-01-31T06:41:30 IST" finished-at="2021-01-31T06:41:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testException -->
      </class> <!-- com.automation.PracticeSeleniumFramework.JavaPractice.RunTimeException -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
